services:
  pgdatabase:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5000:5432"
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    networks:
      - pg-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8000:80"
    networks:
      - pg-network

networks:
  pg-network:
    external: true